export function numberToWordsEs(n: number): string {
  if (isNaN(n) || n < 0) return "";
  if (n === 0) return "CERO";

  const ones = [
    "", "UN", "DOS", "TRES", "CUATRO", "CINCO", "SEIS", "SIETE", "OCHO", "NUEVE",
    "DIEZ", "ONCE", "DOCE", "TRECE", "CATORCE", "QUINCE", "DIECISÉIS", "DIECISIETE",
    "DIECIOCHO", "DIECINUEVE",
  ];
  const veintis = [
    "", "VEINTIUNO", "VEINTIDÓS", "VEINTITRÉS", "VEINTICUATRO", "VEINTICINCO",
    "VEINTISÉIS", "VEINTISIETE", "VEINTIOCHO", "VEINTINUEVE",
  ];
  const tens = ["", "DIEZ", "VEINTE", "TREINTA", "CUARENTA", "CINCUENTA", "SESENTA", "SETENTA", "OCHENTA", "NOVENTA"];
  const hundreds = [
    "", "CIENTO", "DOSCIENTOS", "TRESCIENTOS", "CUATROCIENTOS", "QUINIENTOS",
    "SEISCIENTOS", "SETECIENTOS", "OCHOCIENTOS", "NOVECIENTOS",
  ];

  function chunk(value: number): string {
    if (value === 0) return "";
    if (value < 20) return ones[value];
    if (value < 30) return veintis[value - 20];
    if (value < 100) {
      const remainder = value % 10;
      return remainder === 0 ? tens[Math.floor(value / 10)] : `${tens[Math.floor(value / 10)]} Y ${ones[remainder]}`;
    }
    if (value === 100) return "CIEN";
    const hundred = Math.floor(value / 100);
    const remainder = value % 100;
    return remainder === 0 ? hundreds[hundred] : `${hundreds[hundred]} ${chunk(remainder)}`;
  }

  const integer = Math.floor(n);
  if (integer < 1000) return chunk(integer);
  if (integer < 1_000_000) {
    const thousands = Math.floor(integer / 1000);
    const remainder = integer % 1000;
    const prefix = thousands === 1 ? "MIL" : `${chunk(thousands)} MIL`;
    return remainder === 0 ? prefix : `${prefix} ${chunk(remainder)}`;
  }

  const millions = Math.floor(integer / 1_000_000);
  const remainder = integer % 1_000_000;
  const prefix = millions === 1 ? "UN MILLÓN" : `${chunk(millions)} MILLONES`;
  if (remainder === 0) return prefix;
  const remainderPart = remainder < 1000 ? chunk(remainder) : numberToWordsEs(remainder);
  return `${prefix} ${remainderPart}`;
}

export function amountInWords(amount: string): string {
  const numericAmount = parseFloat(amount);
  if (isNaN(numericAmount) || amount === "") return "";

  const integer = Math.floor(numericAmount);
  const cents = Math.round((numericAmount - integer) * 100);
  let result = numberToWordsEs(integer);
  if (cents > 0) result += ` CON ${numberToWordsEs(cents)} CENTAVOS`;
  return result;
}

export function legacyAmountInWords(amount: string, currency: string): string {
  const numericAmount = parseFloat(amount);
  if (isNaN(numericAmount) || amount === "") return "";

  const currencyLabel =
    currency === "USD" ? "DÓLARES ESTADOUNIDENSES" :
    currency === "UYU" ? "PESOS URUGUAYOS" :
    currency;

  const integer = Math.floor(numericAmount);
  const cents = Math.round((numericAmount - integer) * 100);
  let result = `${numberToWordsEs(integer)} ${currencyLabel}`;
  if (cents > 0) result += ` CON ${numberToWordsEs(cents)} CENTAVOS`;
  return result;
}

export function isAutoGeneratedPriceInWords(value: string, amount: string, currency: string): boolean {
  const current = value.trim();
  if (!current) return true;

  return current === amountInWords(amount).trim() || current === legacyAmountInWords(amount, currency).trim();
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function normalizePriceInWords(value: unknown): string {
  const raw = String(value || "").replace(/\s+/g, " ").trim();
  if (!raw) return "___";

  const currencyPhrases = [
    "dólares billetes estadounidenses",
    "dolares billetes estadounidenses",
    "dólares estadounidenses",
    "dolares estadounidenses",
    "pesos uruguayos",
    "peso uruguayo",
    "dólares billetes",
    "dolares billetes",
    "dólares",
    "dolares",
    "pesos",
  ];

  let normalized = raw;
  for (const phrase of currencyPhrases) {
    const escapedPhrase = escapeRegExp(phrase);
    normalized = normalized.replace(new RegExp(`^${escapedPhrase}\\s+`, "i"), "");
    normalized = normalized.replace(new RegExp(`\\s+${escapedPhrase}$`, "i"), "");
  }

  return normalized.replace(/\s+/g, " ").trim() || "___";
}

export interface PriceTextInput {
  price_currency?: unknown;
  price_amount?: unknown;
  price_in_words?: unknown;
  payment_type?: unknown;
  payment_installments_count?: unknown;
  payment_installment_amount?: unknown;
  payment_detail?: unknown;
  payment_cash_amount?: unknown;
  payment_bank_name?: unknown;
  payment_third_party_name?: unknown;
}

function formatPriceAmount(amount: unknown): string {
  const numericAmount = parseFloat(String(amount));
  if (isNaN(numericAmount)) return String(amount || "___");
  return numericAmount.toLocaleString("es-UY", { minimumFractionDigits: 0, maximumFractionDigits: 2 });
}

export function buildPriceParts(tx: PriceTextInput): {
  moneda: string;
  monto: string;
  pago: string;
} {
  const moneda = tx.price_currency === "USD"
    ? "dólares estadounidenses"
    : "pesos uruguayos";
  const symbol = tx.price_currency === "USD" ? "U$S" : "$";
  const amount = formatPriceAmount(tx.price_amount);
  const words = normalizePriceInWords(tx.price_in_words);
  const monto = `${words} (${symbol} ${amount}, oo)`;

  let pago: string;
  switch (tx.payment_type) {
    case "contado":
      pago = ", pagaderos al contado, en este acto, suma por la cual la parte vendedora entrega a la parte compradora carta total y eficaz de pago por el total del precio estipulado, declarando no tener más nada que reclamar por ningún concepto. -";
      break;
    case "contado_cheque":
      pago = `, que se abona totalmente en este acto, mediante cheque de ${tx.payment_bank_name || "___"}, suma por la cual se otorga total y eficaz carta de pago.`;
      break;
    case "contado_transferencia":
      pago = `, que se abona totalmente en este acto, mediante transferencia bancaria de ${tx.payment_bank_name || "___"}, suma por la cual se otorga total carta de pago.`;
      break;
    case "saldo_precio":
      pago = `, pagaderos en ${tx.payment_installments_count || "___"} cuotas de ${symbol} ${formatPriceAmount(tx.payment_installment_amount)} cada una. ${tx.payment_detail || ""}`;
      break;
    case "mixto":
      pago = `, parte al contado (${symbol} ${formatPriceAmount(tx.payment_cash_amount)}) y ${tx.payment_detail || "saldo en cuotas"}, suma por la cual se otorga total carta de pago.`;
      break;
    case "letra_cambio":
      pago = `, que se abonan mediante letra de cambio${tx.payment_bank_name ? ` emitida por ${tx.payment_bank_name}` : ""}${tx.payment_detail ? `. ${tx.payment_detail}` : "."}`;
      break;
    case "cesion_tercero":
      pago = `, que se abonan mediante cesión a favor de tercero${tx.payment_third_party_name ? ` (${tx.payment_third_party_name})` : ""}${tx.payment_detail ? `. ${tx.payment_detail}` : "."}.`;
      break;
    default:
      pago = ", que fueron abonados antes de este acto, suma por la cual la parte vendedora otorga total carta de pago.";
  }

  return { moneda, monto, pago };
}