import { describe, expect, it } from "vitest";

import { amountInWords, buildPriceParts, isAutoGeneratedPriceInWords, normalizePriceInWords } from "./price-words";

describe("amountInWords", () => {
  it("genera sólo el número en letras sin la moneda", () => {
    expect(amountInWords("18490")).toBe("DIECIOCHO MIL CUATROCIENTOS NOVENTA");
  });

  it("mantiene los centavos cuando existen", () => {
    expect(amountInWords("10990.5")).toBe("DIEZ MIL NOVECIENTOS NOVENTA CON CINCUENTA CENTAVOS");
  });

  it("devuelve CERO cuando el monto es cero", () => {
    expect(amountInWords("0")).toBe("CERO");
  });

  it("convierte montos en millones", () => {
    expect(amountInWords("1000000")).toBe("UN MILLÓN");
  });
});

describe("isAutoGeneratedPriceInWords", () => {
  it("reconoce el formato nuevo autogenerado", () => {
    expect(isAutoGeneratedPriceInWords("DIEZ MIL NOVECIENTOS NOVENTA", "10990", "USD")).toBe(true);
  });

  it("reconoce el formato legado que incluía moneda", () => {
    expect(isAutoGeneratedPriceInWords("DIEZ MIL NOVECIENTOS NOVENTA DÓLARES ESTADOUNIDENSES", "10990", "USD")).toBe(true);
  });

  it("no pisa un valor editado manualmente", () => {
    expect(isAutoGeneratedPriceInWords("DIEZ MIL NOVECIENTOS NOVENTA APROX.", "10990", "USD")).toBe(false);
  });
});

describe("normalizePriceInWords", () => {
  it("limpia moneda legado al final", () => {
    expect(normalizePriceInWords("DIEZ MIL NOVECIENTOS NOVENTA DÓLARES ESTADOUNIDENSES")).toBe("DIEZ MIL NOVECIENTOS NOVENTA");
  });

  it("limpia moneda legado al inicio", () => {
    expect(normalizePriceInWords("dólares billetes estadounidenses Diez Mil Novecientos Noventa")).toBe("Diez Mil Novecientos Noventa");
  });
});

describe("buildPriceParts", () => {
  it("arma la cláusula de contado con la moneda fuera del monto en letras", () => {
    expect(buildPriceParts({
      price_currency: "USD",
      price_amount: "18490",
      price_in_words: "DIECIOCHO MIL CUATROCIENTOS NOVENTA DÓLARES ESTADOUNIDENSES",
      payment_type: "contado",
    })).toEqual({
      moneda: "dólares estadounidenses",
      monto: "DIECIOCHO MIL CUATROCIENTOS NOVENTA (U$S 18.490, oo)",
      pago: ", pagaderos al contado, en este acto, suma por la cual la parte vendedora entrega a la parte compradora carta total y eficaz de pago por el total del precio estipulado, declarando no tener más nada que reclamar por ningún concepto. -",
    });
  });

  it("arma saldo de precio con símbolo y detalle", () => {
    expect(buildPriceParts({
      price_currency: "USD",
      price_amount: "22500",
      price_in_words: "VEINTIDÓS MIL QUINIENTOS",
      payment_type: "saldo_precio",
      payment_installments_count: "6",
      payment_installment_amount: "1000",
      payment_detail: "Cuotas mensuales y consecutivas.",
    })).toEqual({
      moneda: "dólares estadounidenses",
      monto: "VEINTIDÓS MIL QUINIENTOS (U$S 22.500, oo)",
      pago: ", pagaderos en 6 cuotas de U$S 1.000 cada una. Cuotas mensuales y consecutivas.",
    });
  });

  it("arma pago con cheque", () => {
    expect(buildPriceParts({
      price_currency: "USD",
      price_amount: "15000",
      price_in_words: "QUINCE MIL",
      payment_type: "contado_cheque",
      payment_bank_name: "BROU",
    })).toEqual({
      moneda: "dólares estadounidenses",
      monto: "QUINCE MIL (U$S 15.000, oo)",
      pago: ", que se abona totalmente en este acto, mediante cheque de BROU, suma por la cual se otorga total y eficaz carta de pago.",
    });
  });

  it("arma pago mixto con fallback de detalle", () => {
    expect(buildPriceParts({
      price_currency: "USD",
      price_amount: "12000",
      price_in_words: "DOCE MIL",
      payment_type: "mixto",
      payment_cash_amount: "3000",
    })).toEqual({
      moneda: "dólares estadounidenses",
      monto: "DOCE MIL (U$S 12.000, oo)",
      pago: ", parte al contado (U$S 3.000) y saldo en cuotas, suma por la cual se otorga total carta de pago.",
    });
  });

  it("arma pago por letra de cambio con banco y detalle", () => {
    expect(buildPriceParts({
      price_currency: "USD",
      price_amount: "23000",
      price_in_words: "VEINTITRÉS MIL",
      payment_type: "letra_cambio",
      payment_bank_name: "Banco República",
      payment_detail: "Serie A, número 12345",
    })).toEqual({
      moneda: "dólares estadounidenses",
      monto: "VEINTITRÉS MIL (U$S 23.000, oo)",
      pago: ", que se abonan mediante letra de cambio emitida por Banco República. Serie A, número 12345",
    });
  });

  it("arma pago por cesión a tercero con nombre y detalle", () => {
    expect(buildPriceParts({
      price_currency: "USD",
      price_amount: "18000",
      price_in_words: "DIECIOCHO MIL",
      payment_type: "cesion_tercero",
      payment_third_party_name: "Juan Pérez",
      payment_detail: "Cesión gratuita del saldo de precio",
    })).toEqual({
      moneda: "dólares estadounidenses",
      monto: "DIECIOCHO MIL (U$S 18.000, oo)",
      pago: ", que se abonan mediante cesión a favor de tercero (Juan Pérez). Cesión gratuita del saldo de precio.",
    });
  });

  it("usa el fallback de pago cuando no hay payment_type", () => {
    expect(buildPriceParts({
      price_currency: "UYU",
      price_amount: "250000",
      price_in_words: "DOSCIENTOS CINCUENTA MIL",
    })).toEqual({
      moneda: "pesos uruguayos",
      monto: "DOSCIENTOS CINCUENTA MIL ($ 250.000, oo)",
      pago: ", que fueron abonados antes de este acto, suma por la cual la parte vendedora otorga total carta de pago.",
    });
  });
});